############# Italian navigation ##############

# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Quiénes somos"
url = "about/"
weight = 2

[[main]]
name = "Servicio"
url = "service/"
weight = 3

#[[main]]
#name = "Proyecto"
#url = "project/"
#weight = 3

#[[main]]
#name = "Blog"
#url = "blog/"
#weight = 4

[[main]]
weight = 5
name = "Más"
hasChildren = true

  #[[main]]
  #parent = "Más"
  #name = "Servicio"
  #url = "service/"
  #weight = 1

  #[[main]]
  #parent = "Más"
  #name = "Tarifas"
  #url = "pricing/"
  #weight = 2

  [[main]]
  parent = "Más"
  name = "FAQ"
  url = "faq/"
  weight = 3
  
[[main]]
name = "Contacto"
url = "contact/"
weight = 6

[[main]]
name = "Acceso"
url = "https://app.quko.es/"
weight = 7


# footer menu
[[footer]]
name = "Quiénes somos"
url = "about/"
weight = 2

#[[footer]]
#name = "Proyecto"
#url = "project/"
#weight = 3

[[footer]]
name = "Servicio"
url = "service/"
weight = 4

#[[footer]]
#name = "Tarifas"
#url = "pricing/"
#weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contacto"
url = "contact/"
weight = 7
