############# Italian navigation ##############

# main menu
[[main]]
name = "Inicio"
url = ""
weight = 1

[[main]]
name = "Quen somos"
url = "about/"
weight = 2

[[main]]
name = "Proxecto"
url = "project/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

[[main]]
weight = 5
name = "M치is"
hasChildren = true

  [[main]]
  parent = "M치is"
  name = "Servizo"
  url = "service/"
  weight = 1

  [[main]]
  parent = "M치is"
  name = "Prezos"
  url = "pricing/"
  weight = 2

  [[main]]
  parent = "M치is"
  name = "FAQ"
  url = "faq/"
  weight = 3
  
[[main]]
name = "Contato"
url = "contact/"
weight = 6


# footer menu
[[footer]]
name = "Quen somos"
url = "about/"
weight = 2

[[footer]]
name = "Proxecto"
url = "project/"
weight = 3

[[footer]]
name = "Servizo"
url = "service/"
weight = 4

[[footer]]
name = "Prezos"
url = "pricing/"
weight = 5

[[footer]]
name = "FAQ"
url = "faq/"
weight = 6

[[footer]]
name = "Contaco"
url = "contact/"
weight = 7
